# This workflow runs poetry against the repository.
#
# You can adjust the behavior by modifying this file.
name: Run poetry

on: [pull_request]

permissions:
  contents: read

jobs:
  poetry:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        python-version:
          - "3.7"  # EOL 2023-06-27
          - "3.8"  # EOL 2024-10
          - "3.9"  # EOL 2025-10
          - "3.10"  # EOL 2026-10
          - "3.11"  # EOL 2027-10
        experimental: [false]
        include:
          - python-version: 3.x
            experimental: true
    steps:
      - uses: actions/checkout@v2
      - name: setup python-${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: cache poetry
        uses: actions/cache@v2
        with:
          path: ~/.cache/poetry
          key:  ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: ${{ runner.os }}-poetry-
      - name: install poetry
        run: pip --no-python-version-warning install poetry
      - name: poetry build
        run: |
          poetry build
          tar -zvtf dist/template_py-*.tar.gz | grep template
      - name: poetry check
        run: poetry check
